### ISSUE TITLE
Rounded corner cover in grid view

### ISSUE THREAD

**Issue by maicol07** [sakasakiking/FusionX#12]
Hi,
can you add the rounded corners in grid view?
Thanks

**Comment by sakasakiking** [comment]
What do you mean here? The whole GridOverVIew? It'd better have a screenshot to help me understand. Thanks.

**Comment by Slythebadguy** [comment]
I think they're talking about the window border having straight corners. It kinda clashes with windows 11 rounded corners and the rest of the rounded ui elements. 
![{95B7851C-0386-4771-B638-E649ADB8AED9}](https://github.com/user-attachments/assets/a09a0159-fc51-4e84-8788-7f17a6e42074)

**Comment by sakasakiking** [comment]
Got it and thanks for the feedback. I don‘t suggest to add the corner-radius on windows, because it does not look good with jagged edges and I can make it better by changing the theme files. For the game image cover (game cards), yeah, that's OK. But one thing you should know, the rounded corner will slow down the programme reacting speed.

**Comment by sakasakiking** [comment]
Due to it's been updated, I close it.
